llama_server_path = 'D:/llama-truboquant/build/bin/Release/llama-server.exe'
model = 'D:/LLM Model File/Qwen3.6-27B-uncensored-heretic-v2-Native-MTP-Preserved-Q4_K_M.gguf'
host = '0.0.0.0'
port = 8080
ctx_size = 128000
n_predict = -1
n_gpu_layers = 999
chat_template_kwargs = '{"enable_thinking":true,"preserve_thinking":true}'
temp = 0.6
top_k = 20
top_p = 0.95
min_p = 0.0
presence_penalty = 1.0
batch_size = 2048
verbose = true
log_verbosity = 3
webui = true
embeddings = false
continuous_batching = false
cpu_moe = false
n_cpu_moe = 0
split_mode = 'layer'
tensor_split = ''
main_gpu = 0
flash_attn = 'on'
fit = 'off'
fit_target = ''
kv_offload = 'auto'
mmap = true
mlock = false
mmproj = 'I:/model/mmproj-BF16.gguf'
mmproj_enabled = false
threads = 6
ubatch_size = 512
cache_type_k = 'turbo3'
cache_type_v = 'turbo3'
threads_batch = 6
frequency_penalty = 0.0
repeat_penalty = 1.0
repeat_last_n = 64
typical = 1.0
seed = -1
rope_scaling = ''
rope_scale = 0.0
rope_freq_base = 0.0
rope_freq_scale = 0.0
keep = 0
numa = ''
device = ''
fit_ctx = 4096
parallel = -1
timeout = 2400
threads_http = -1
reasoning = 'on'
reasoning_budget = -1
reasoning_format = 'auto'
pooling = ''
alias = ''
tags = ''
lora = ''
slot_save_path = ''
models_dir = ''
t_max_predict_ms = 2400
sleep_idle_seconds = 4800
max_tokens = -1
kv_unified = true
max_output_tokens = 0
n_parallel = 1
reasoning_enabled = false
enable_thinking = false
moe_expert_count = -1
tools = 'all'
custom_args = ''
spec_draft_n_max = '3'
spec_type = 'draft-mtp'
n_gpu_layers_draft = ''
model_draft = ''
spec_draft_p_min = ''
window_geometry = '1185x852+74+81'
model_root = 'D:/LLM Model File'
