"""默认配置字典（首次运行 / config.toml 不存在时使用）。"""

import os

DEFAULT_CONFIG = {
    "llama_server_path": "",
    "model_root": os.path.join(
        os.path.dirname(os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))),
        "model",
    ),
    "model": "",
    "host": "0.0.0.0",
    "port": 8080,
    "ctx_size": 96000,
    "n_predict": -1,
    "chat_template_kwargs": '{}',
    "temp": 0.6,
    "top_k": 20,
    "top_p": 0.95,
    "min_p": 0.0,
    "presence_penalty": 0.0,
    "batch_size": 2048,
    "ubatch_size": 512,
    "threads": 0,
    "threads_batch": 0,
    "cpu_moe": False,
    "n_cpu_moe": 0,
    "moe_expert_count": -1,
    "split_mode": "layer",
    "tensor_split": "",
    "main_gpu": 0,
    "flash_attn": "auto",
    "fit": "on",
    "mlock": False,
    "verbose": True,
    "log_verbosity": 3,
    "webui": True,
    "embeddings": False,
    "continuous_batching": True,
    "mmproj": "",
    "mmproj_enabled": False,
    "n_parallel": -1,
    "timeout": 0,
    "sleep_idle_seconds": 0,
    "tools": "",
    "repeat_penalty": 1.0,
    "repeat_last_n": 64,
    "seed": -1,
    "cache_type_k": "",
    "cache_type_v": "",
    "spec_type": "",
    "spec_draft_n_max": "",
    "spec_draft_p_min": "",
    "n_gpu_layers_draft": "",
    "model_draft": "",
    "custom_args": "",
    "window_geometry": "1080x780",
}
